### PR TITLE
Added volumes for additional menu entries and TFTP shared content

### PR DESCRIPTION
**Pull request by smasset**

### CODE REVIEW

**Comment by ferrarimarco** [comment]
hi @smasset ! thx for the PR :)

Can you explain the use case?

**Comment by smasset** [comment]
Hi and thanks for the quick reply.

Use case is pretty simple : being able to add extra config and data by mounting volumes instead of building whole image again.

**Comment by ferrarimarco** [comment]
I'm not against this idea, but why the path change? Can't you just add a VOLUME instruction?

**Comment by ferrarimarco** [comment]
Clsoing waiting for a reply. Please ping again if you've an answer :)

**Pull request closed without merging**
