### PR TITLE
fix "ARP-cache injection failed: Operation not permitted"

### PR DESCRIPTION
**Pull request by luxigo**

### CODE REVIEW

**Comment by ferrarimarco** [comment]
Hi @luxigo ! Thx for the PR.

Can you please share some details (like output) on what you're trying to fix?

Thanks!

**Comment by luxigo** [comment]
Hey @ferrarimarco !

Running on Debian 10 from command line I have the mentioned error and running the container as root did not fix it.

With a little help from stackoverflow I found that  " For some reason, dnsmasq was trying to unicast the DHCPOFFER messages, and it was using ARP to try to get an address that had not yet been assigned."  and the proposed dnsmasq flag solve this.

Source: https://stackoverflow.com/questions/38816077/run-dnsmasq-as-dhcp-server-from-inside-a-docker-container/39448493#39448493

**Comment by ferrarimarco** [comment]
Ok, I finally had time to review this.

According to [dnsmasq docs](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html):

> --dhcp-broadcast[=tag:<tag>[,tag:<tag>]]
> (IPv4 only) When all the given tags appear in the tag set, always use broadcast to communicate with the host when it is unconfigured. It is permissible to supply no tags, in which case this is unconditional. Most DHCP clients which need broadcast replies set a flag in their requests so that this happens automatically, some old BOOTP clients do not.

So that flag is basically to be compatible with old BOOTP clients. Is this your case?

**Comment by ferrarimarco** [comment]
Closing waiting for a reply. Please ping again if you have more insights :)

**Pull request closed without merging**
